###
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "sujith@example.com",
  "password": "secret123"
}


###

POST http://localhost:8080/tasks/john@example.com
Content-Type: application/json

{
  "title": "Good",
  "taskDate": "2025-09-12"
}
###